# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alien/Documents/flocking-opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alien/Documents/flocking-opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alien/Documents/flocking-opengl/CMakeFiles /home/alien/Documents/flocking-opengl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alien/Documents/flocking-opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named flocking

# Build rule for target.
flocking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flocking
.PHONY : flocking

# fast build rule for target.
flocking/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/build
.PHONY : flocking/fast

flocking/src/boids/boid.o: flocking/src/boids/boid.cpp.o
.PHONY : flocking/src/boids/boid.o

# target to build an object file
flocking/src/boids/boid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/boids/boid.cpp.o
.PHONY : flocking/src/boids/boid.cpp.o

flocking/src/boids/boid.i: flocking/src/boids/boid.cpp.i
.PHONY : flocking/src/boids/boid.i

# target to preprocess a source file
flocking/src/boids/boid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/boids/boid.cpp.i
.PHONY : flocking/src/boids/boid.cpp.i

flocking/src/boids/boid.s: flocking/src/boids/boid.cpp.s
.PHONY : flocking/src/boids/boid.s

# target to generate assembly for a file
flocking/src/boids/boid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/boids/boid.cpp.s
.PHONY : flocking/src/boids/boid.cpp.s

flocking/src/camera.o: flocking/src/camera.cpp.o
.PHONY : flocking/src/camera.o

# target to build an object file
flocking/src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/camera.cpp.o
.PHONY : flocking/src/camera.cpp.o

flocking/src/camera.i: flocking/src/camera.cpp.i
.PHONY : flocking/src/camera.i

# target to preprocess a source file
flocking/src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/camera.cpp.i
.PHONY : flocking/src/camera.cpp.i

flocking/src/camera.s: flocking/src/camera.cpp.s
.PHONY : flocking/src/camera.s

# target to generate assembly for a file
flocking/src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/camera.cpp.s
.PHONY : flocking/src/camera.cpp.s

flocking/src/main.o: flocking/src/main.cpp.o
.PHONY : flocking/src/main.o

# target to build an object file
flocking/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/main.cpp.o
.PHONY : flocking/src/main.cpp.o

flocking/src/main.i: flocking/src/main.cpp.i
.PHONY : flocking/src/main.i

# target to preprocess a source file
flocking/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/main.cpp.i
.PHONY : flocking/src/main.cpp.i

flocking/src/main.s: flocking/src/main.cpp.s
.PHONY : flocking/src/main.s

# target to generate assembly for a file
flocking/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/main.cpp.s
.PHONY : flocking/src/main.cpp.s

flocking/src/solids/cube.o: flocking/src/solids/cube.cpp.o
.PHONY : flocking/src/solids/cube.o

# target to build an object file
flocking/src/solids/cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/cube.cpp.o
.PHONY : flocking/src/solids/cube.cpp.o

flocking/src/solids/cube.i: flocking/src/solids/cube.cpp.i
.PHONY : flocking/src/solids/cube.i

# target to preprocess a source file
flocking/src/solids/cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/cube.cpp.i
.PHONY : flocking/src/solids/cube.cpp.i

flocking/src/solids/cube.s: flocking/src/solids/cube.cpp.s
.PHONY : flocking/src/solids/cube.s

# target to generate assembly for a file
flocking/src/solids/cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/cube.cpp.s
.PHONY : flocking/src/solids/cube.cpp.s

flocking/src/solids/pyramid.o: flocking/src/solids/pyramid.cpp.o
.PHONY : flocking/src/solids/pyramid.o

# target to build an object file
flocking/src/solids/pyramid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/pyramid.cpp.o
.PHONY : flocking/src/solids/pyramid.cpp.o

flocking/src/solids/pyramid.i: flocking/src/solids/pyramid.cpp.i
.PHONY : flocking/src/solids/pyramid.i

# target to preprocess a source file
flocking/src/solids/pyramid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/pyramid.cpp.i
.PHONY : flocking/src/solids/pyramid.cpp.i

flocking/src/solids/pyramid.s: flocking/src/solids/pyramid.cpp.s
.PHONY : flocking/src/solids/pyramid.s

# target to generate assembly for a file
flocking/src/solids/pyramid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/pyramid.cpp.s
.PHONY : flocking/src/solids/pyramid.cpp.s

flocking/src/solids/solid.o: flocking/src/solids/solid.cpp.o
.PHONY : flocking/src/solids/solid.o

# target to build an object file
flocking/src/solids/solid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/solid.cpp.o
.PHONY : flocking/src/solids/solid.cpp.o

flocking/src/solids/solid.i: flocking/src/solids/solid.cpp.i
.PHONY : flocking/src/solids/solid.i

# target to preprocess a source file
flocking/src/solids/solid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/solid.cpp.i
.PHONY : flocking/src/solids/solid.cpp.i

flocking/src/solids/solid.s: flocking/src/solids/solid.cpp.s
.PHONY : flocking/src/solids/solid.s

# target to generate assembly for a file
flocking/src/solids/solid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flocking.dir/build.make CMakeFiles/flocking.dir/flocking/src/solids/solid.cpp.s
.PHONY : flocking/src/solids/solid.cpp.s

flocking/vendor/glad/src/glad.o: flocking/vendor/glad/src/glad.c.o
.PHONY : flocking/vendor/glad/src/glad.o

# target to build an object file
flocking/vendor/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/flocking/vendor/glad/src/glad.c.o
.PHONY : flocking/vendor/glad/src/glad.c.o

flocking/vendor/glad/src/glad.i: flocking/vendor/glad/src/glad.c.i
.PHONY : flocking/vendor/glad/src/glad.i

# target to preprocess a source file
flocking/vendor/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/flocking/vendor/glad/src/glad.c.i
.PHONY : flocking/vendor/glad/src/glad.c.i

flocking/vendor/glad/src/glad.s: flocking/vendor/glad/src/glad.c.s
.PHONY : flocking/vendor/glad/src/glad.s

# target to generate assembly for a file
flocking/vendor/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/flocking/vendor/glad/src/glad.c.s
.PHONY : flocking/vendor/glad/src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flocking"
	@echo "... glad"
	@echo "... flocking/src/boids/boid.o"
	@echo "... flocking/src/boids/boid.i"
	@echo "... flocking/src/boids/boid.s"
	@echo "... flocking/src/camera.o"
	@echo "... flocking/src/camera.i"
	@echo "... flocking/src/camera.s"
	@echo "... flocking/src/main.o"
	@echo "... flocking/src/main.i"
	@echo "... flocking/src/main.s"
	@echo "... flocking/src/solids/cube.o"
	@echo "... flocking/src/solids/cube.i"
	@echo "... flocking/src/solids/cube.s"
	@echo "... flocking/src/solids/pyramid.o"
	@echo "... flocking/src/solids/pyramid.i"
	@echo "... flocking/src/solids/pyramid.s"
	@echo "... flocking/src/solids/solid.o"
	@echo "... flocking/src/solids/solid.i"
	@echo "... flocking/src/solids/solid.s"
	@echo "... flocking/vendor/glad/src/glad.o"
	@echo "... flocking/vendor/glad/src/glad.i"
	@echo "... flocking/vendor/glad/src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

