#ifndef GL_BINDINGS_H
#define GL_BINDINGS_H

#include <glad/glad.h>


// VERTEX SHADER INPUTS
const GLuint POSITION_ATTRIB_LOC = 0;
const GLuint NORMAL_ATTRIB_LOC = 1;
const GLuint TEXCOORD_ATTRIB_LOC = 2;
const GLuint MODEL_MATRIX_ATTRIB_LOC = 3;


// BASE_INSTANCE SHADERS BUFFERS
const GLuint PROJ_VIEW_UBO_BINDING = 0;
const GLuint NODEPRIM_PROPERTIES_SSBO_BINDING = 1;
const GLuint PRIMITIVE_PROPERTIES_SSBO_BINDING = 2;
const GLuint VISIBLE_INSTANCES_SSBO_BINDING = 3;
const GLuint WORLD_FROM_MODEL_SSBO_BINDING = 4;
const GLuint NODE_PROPERTIES_SSBO_BINDING = 5;
const GLuint MATERIAL_PROPERTIES_SSBO_BINDING = 6;
const GLuint TEXTURES_SSBO_BINDING = 7;


// FRAGMENT SHADER INPUTS
const GLuint ALBEDO_TEXTURE_BINDING = 4;
const GLuint MATERIAL_UBO_BINDING = 5;

// CULLING SHADER BUFFERS
const GLuint CULLING_WORLD_FROM_MODEL_SSBO_BINDING = 4;
const GLuint CULLING_FRUSTUM_CULL_DATA_UBO_BINDING = 8;
const GLuint CULLING_VISIBLE_INSTANCES_SSBO_BINDING = 3;

// INST COUNT SETTING
const GLuint INSTCOUNT_SET_VISIBLE_INSTANCES_SSBO_BINDING = 3;
const GLuint INSTCOUNT_SET_DRAW_CMD_BUFFER_SSBO_BINDING = 9;
const GLuint INSTCOUNT_SET_DRAW_CMD_COUNT_SSBO_BINDING = 10;

// SCREEN SHADER INPUTS
const GLuint SCREEN_TEXTURE_BINDING = 4;


#endif